targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/common/domain/{{}}.dart': 'lib/common/domain/generated/{{}}.g.dart'