name: dishful
description: A recipe development app.
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^1.0.3
  fluro: ^2.0.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  nanoid: ^1.0.0
  faker: ^2.0.0
  json_annotation: ^4.4.0

  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5
  firebase_auth: ^3.3.4
  async: ^2.8.2
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
