name: dishful
description: A recipe development app.
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^1.0.0-dev.6
  fluro: ^2.0.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  nanoid: ^1.0.0
  faker: ^2.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
