name: dishful
description: A recipe development app.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

scripts:
  start: flutter run -d chrome
  start_mock: $start --dart-define isMock=true
  start_debug: $start --dart-define isMock=false
  generate: flutter pub run build_runner build

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.0.1
  loading_animation_widget: ^1.1.0+5

  flutter_riverpod: ^2.0.0-dev.9
  go_router: ^4.3.0
  fluro: ^2.0.3

  hive: ^2.0.4
  hive_flutter: ^1.1.0

  shared_preferences: ^2.0.15

  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  firebase_storage: ^10.2.17
  cloud_firestore: ^3.1.17
  cloud_functions: ^3.2.16

  flutter_form_builder: ^7.0.0
  form_builder_validators: ^8.3.0

  responsive_framework: ^0.2.0
  awesome_extensions: ^2.0.3
  animations: ^2.0.2
  flash: ^2.0.3+2
  flutter_portal: ^1.0.0

  responsive_scaffold_nullsafe: ^1.0.1
  modal_bottom_sheet: ^2.0.1
  parallax_animation: ^0.0.3
  blobs: ^2.0.0
  tab_container: ^2.0.0

  octo_image: ^1.0.1
  cached_network_image: ^3.2.0
  cross_file_image: ^1.0.0
  cross_file: ^0.3.2
  image_picker: ^0.8.4+4
  blurhash_dart: ^1.1.0
  image: ^3.1.1

  json_annotation: ^4.4.0
  copy_with_extension: ^4.0.0
  recase: ^4.0.0
  uuid: ^3.0.5
  faker: ^2.0.0
  html: ^0.15.0
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.3
  copy_with_extension_gen: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 500
    - family: SweetApricot
      fonts:
        - asset: assets/fonts/SweetApricot.ttf
    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo-Regular.ttf
    - family: AvenirNextLTPro
      fonts:
        - asset: assets/fonts/AvenirNextLTPro-Regular.otf
        - asset: assets/fonts/AvenirNextLTPro-It.otf
          style: italic
        - asset: assets/fonts/AvenirNextLTPro-Bold.otf
          weight: 700
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
