name: dishful
description: A recipe development app.
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

scripts:
  start: flutter run -d chrome
  start_mock: derry start -- --dart-define isMock=true
  start_debug: derry start -- --dart-define isMock=false

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  flutter_riverpod: ^1.0.3
  fluro: ^2.0.3

  hive: ^2.0.4
  hive_flutter: ^1.1.0

  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  cloud_firestore: ^3.1.5
  cloud_functions: ^3.2.4

  json_annotation: ^4.4.0
  async: ^2.8.2
  nanoid: ^1.0.0
  faker: ^2.0.0
  html: ^0.15.0
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
